### ISSUE TITLE
Not compatible with OpenComputers: java.lang.ClassCircularityError: scala/Predef$

### ISSUE THREAD

**Issue by Foxxtail1** [AlmuraDev/SGCraft#117]
I've looked this up but basically if Mixin is involved then it causes errors with OpenComputers.

**Comment by Dockter** [comment]
I need something more than this to go on.

**Comment by Foxxtail1** [comment]
[latest.log](https://github.com/AlmuraDev/SGCraft/files/3775368/latest.log)

This happens only when entering a world. The current fix is not have MalisisCore activated, however I loose access to the GDO, PDD and the configuration which are amazing tools. It would seem that Mixin would play around with things it shouldn't when it comes to asm (something about Scala). The newer version of Mixin doesn't act this way anymore (as of 0.7.11 which is currently being used by MalisisCore) but for some reason it still is. So at the moment, sgcraft isn't compatible with OpenComputers if using MalisisCore.

I'm also using Forge not SpongeForge.

Here are my system details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_231, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1089377472 bytes (1038 MB) / 1372585984 bytes (1309 MB) up to 5726797824 bytes (5461 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx6144m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: 
	Loaded coremods (and transformers): 
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  
TransformerLoader (OpenComputers-MC1.12.2-1.7.4.153.jar)
  li.cil.oc.common.asm.ClassTransformer
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.238.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer

Here is the error:
[19:40:29] [main/WARN] [OpenComputers]: Something went wrong!
java.lang.ClassCircularityError: scala/Predef$
	at li.cil.oc.common.asm.ClassTransformer.transform(ClassTransformer.scala:163) [OpenComputers-MC1.12.2-1.7.4.153.jar:?]
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:256) [ASMTransformerWrapper$TransformerWrapper.class:?]
	at org.spongepowered.asm.service.mojang.LegacyTransformerHandle.transformClassBytes(LegacyTransformerHandle.java:71) [malisiscore-1.12.2-6.5.1.jar:1.12.2-6.5.1-SNAPSHOT]
	at org.spongepowered.asm.service.mojang.MixinServiceLaunchWrapper.applyTransformers(MixinServiceLaunchWrapper.java:388) [malisiscore-1.12.2-6.5.1.jar:1.12.2-6.5.1-SNAPSHOT]
	at org.spongepowered.asm.service.mojang.MixinServiceLaunchWrapper.getClassBytes(MixinServiceLaunchWrapper.java:352) [malisiscore-1.12.2-6.5.1.jar:1.12.2-6.5.1-SNAPSHOT]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.loadMixinClass(MixinInfo.java:1167) [malisiscore-1.12.2-6.5.1.jar:1.12.2-6.5.1-SNAPSHOT]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:788) [malisiscore-1.12.2-6.5.1.jar:1.12.2-6.5.1-SNAPSHOT]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:569) [malisiscore-1.12.2-6.5.1.jar:1.12.2-6.5.1-SNAPSHOT]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:502) [malisiscore-1.12.2-6.5.1.jar:1.12.2-6.5.1-SNAPSHOT]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.prepareConfigs(MixinTransformer.java:647) [malisiscore-1.12.2-6.5.1.jar:1.12.2-6.5.1-SNAPSHOT]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.select(MixinTransformer.java:572) [malisiscore-1.12.2-6.5.1.jar:1.12.2-6.5.1-SNAPSHOT]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.checkSelect(MixinTransformer.java:548) [malisiscore-1.12.2-6.5.1.jar:1.12.2-6.5.1-SNAPSHOT]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:451) [malisiscore-1.12.2-6.5.1.jar:1.12.2-6.5.1-SNAPSHOT]
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) [malisiscore-1.12.2-6.5.1.jar:1.12.2-6.5.1-SNAPSHOT]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) [launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) [?:1.8.0_231]
	at java.lang.ClassLoader.loadClass(Unknown Source) [?:1.8.0_231]
	at net.minecraftforge.fml.common.asm.transformers.EventSubscriptionTransformer.buildEvents(EventSubscriptionTransformer.java:106) [forge-1.12.2-14.23.5.2816-universal.jar:?]
	at net.minecraftforge.fml.common.asm.transformers.EventSubscriptionTransformer.transform(EventSubscriptionTransformer.java:82) [forge-1.12.2-14.23.5.2816-universal.jar:?]
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:256) [ASMTransformerWrapper$TransformerWrapper.class:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) [launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) [?:1.8.0_231]
	at java.lang.ClassLoader.loadClass(Unknown Source) [?:1.8.0_231]
	at li.cil.oc.common.asm.ClassTransformer.transform(ClassTransformer.scala:163) [OpenComputers-MC1.12.2-1.7.4.153.jar:?]
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:256) [ASMTransformerWrapper$TransformerWrapper.class:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) [launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) [?:1.8.0_231]
	at java.lang.ClassLoader.loadClass(Unknown Source) [?:1.8.0_231]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_231]
	at java.lang.Class.forName(Unknown Source) [?:1.8.0_231]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_231]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_231]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_231]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_231]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]

**Comment by Foxxtail1** [comment]
The error is the same if MalisisCore isn't there, sgcraft takes its place in the error stack.

**Comment by Dockter** [comment]
OK, so this is a complicated answer.  Something is using Scala.  SGCraft doesn't use it, MalisisCore I'm pretty sure doesn't use it but one of your other mods does.  

Can you give me a complete list of mods?

**Comment by Foxxtail1** [comment]
Applied Energistics 2 rv6 
CodeChickenLib 3.2.3.358
ForgeMultipart 2.6.2.83
GalacticCraft Planets 4.0.2.238
GalacticCraft Core 4.0.2.238
jei 4.15.0.291
malisiscore 6.5.1
Mantle 1.3.3.49
MicdoodleCore 4.0.2.238
MrTJPCore 2.1.4.43
OpenCopmuters 1.7.4.153
Project Base/Compat/Fabrication/Intergration 4.9.4.120
SGCraft 2.0.2
Tinkers Construct 2.12.0.157

**Comment by Foxxtail1** [comment]
Having looked in the OpenComputers repo, they seem to put the blame on Mixin. MightyPirates/OpenComputers#2840

**Comment by Dockter** [comment]
Mixin doesn't use Scala so they are pointing the wrong way.  I personally talked to Mumfrey about this.

**Comment by Foxxtail1** [comment]
Although Mixin doesn't use scala, scala has to be added to the transform exclusion list. Something I thought was a global fix but aperantly has to be added in manualy. My guess would be to do that in [here](https://github.com/AlmuraDev/SGCraft/blob/850286ab5deb7cbbabaa7be4f91e822368d2762e/src/mod/gcewing/sg/SGCraft.java#L184).

Here is the link to the fix: SpongePowered/Mixin#252

I don't use SpongeForge, just regular Forge so that may be the reason why the fix isn't applied.

**Comment by Foxxtail1** [comment]
That didn't work. Doing like SpongeForge, creating a core mod that adds this exclusion would probably fix it.

**Comment by Foxxtail1** [comment]
Doing as mentioned has cleared this bug for with and without MalisisCore.

**Comment by Foxxtail1** [comment]
This mod fixes this issue; https://www.curseforge.com/minecraft/mc-mods/forge-mixin-fix
