### ISSUE TITLE
Chunk unloading when dialing

### ISSUE THREAD

**Issue by drzpk** [AlmuraDev/SGCraft#26]
Sometimes when I'm trying to dial an address within one dimension, **but using a computer interface**, stargate is disconnecting in the middle of the dialing sequence. But if I'm dialing the same address but from a DHD, everything works fine.

I've added some code in order to locate source of this issue:
```
SGBaseTE.connect: to BlockPos{x=-941, y=70, z=-3407} in dimension 0 with state Idle
SGBaseTE: Server: disconnect()
[13:30:36] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]: java.lang.Exception: Stack trace
[13:30:36] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]: 	at java.lang.Thread.dumpStack(Unknown Source)
[13:30:36] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]: 	at gcewing.sg.SGBaseTE.disconnect(SGBaseTE.java:736)
[13:30:36] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]: 	at gcewing.sg.SGCraft.onChunkUnload(SGCraft.java:366)
[13:30:36] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_614_SGCraft_onChunkUnload_Unload.invoke(.dynamic)
[13:30:36] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
[13:30:36] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]: 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
[13:30:36] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]: 	at net.minecraft.world.chunk.Chunk.func_76623_d(Chunk.java:877)
[13:30:36] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]: 	at net.minecraft.world.gen.ChunkProviderServer.func_73156_b(ChunkProviderServer.java:269)
[13:30:36] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]: 	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:207)
[13:30:36] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]: 	at net.optifine.override.WorldServerOF.func_72835_b(WorldServerOF.java:39)
[13:30:36] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
[13:30:36] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
[13:30:36] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]: 	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
[13:30:36] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
[13:30:36] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]: 	at java.lang.Thread.run(Unknown Source)
[13:30:36] [Server thread/INFO] [STDOUT]: [gcewing.sg.SGCraft:onChunkUnload:367]: Chunk unloaded at: -59, -213
```

**Comment by Dockter** [comment]
What version are you using?

**Comment by MatWein** [comment]
I have the same problem on dialing the stargate with OpenComputers. I'm using:
- OpenComputers-MC1.12.2-1.7.2.67
- SGCraft-1.3-mc1.12.2

**Comment by drzpk** [comment]
In my case it's [91167eb](https://github.com/AlmuraDev/SGCraft/commit/91167eb62687c6b99073b9db2657be1b83299af1).

**Comment by Dockter** [comment]
@IlynPayne that "should" be fine...  @MatWein you are on a too old of a version., use 1.15.5.

@IlynPayne can you give me a full mods list please?

**Comment by Dockter** [comment]
@IlynPayne that stack trace isn't helpful because that is just getting the call to disconnect when the server is telling the chunk to unload.  I fixed this issue in other version in the connect method of SGBaseTE by forcing the chunk load ticket to before the first chevron is locked.

**Comment by drzpk** [comment]
> that stack trace isn't helpful because that is just getting the call to disconnect when the server is telling the chunk to unload.

@Dockter Exactly. Somehow chunk can unload itself even if it was told not to. The log excerpt I provided was merely supposed to confirm that.

Below is the list of mods I'm using. It's worth mentioning that near the chunks I cannot dial to there are some blocks that prevent chunks from unloading (a Mekanism's chunk loading upgrade or a Chicken Chunk's block).

- Advanced+Solar+Panels-4.2.0
- AdvancedRocketry-1.12.2-1.4.0-88-universal
- Aroma1997Core-1.12.2-1.3.0.2
- Aroma1997s-Dimensional-World-1.12-1.3.0.0.b37
- BrandonsCore-1.12.2-2.4.3.168-universal
- ChickenASM-1.12-1.0.2.7
- ChickenChunks-1.12.2-2.4.1.71-universal
- Chisel_DEV-MC1.12.2-0.2.0.2d484ec
- CodeChickenLib-1.12.2-3.2.1.349-universal
- CoFHCore-1.12.2-4.5.2.19-universal
- CoFHWorld-1.12.2-1.2.0.5-universal
- CTM-MC1.12.2-0.3.2.18
- cyberware-1.12.2-0.2.10.13
- Draconic-Evolution-1.12.2-2.3.12.297-universal
- EnderCore-1.12.2-0.5.31
- EnderIO-1.12.2-5.0.26
- energyconverters_1.12.1-1.0.1.2
- ExtremeReactors-1.12.2-0.4.5.49
- FloodLights-1.12.2-1.3.0-0
- ForgeMultipart-1.12.2-2.5.0.null-universal
- geneticsreborn-1.12-1.09
- Hwyla-1.8.26-B41_1.12.2
- ICBM-classic-1.12.2-3.1.0b41
- industrialcraft-2-2.8.90-ex112
- IronBackpacks-1.12.2-3.0.8-12
- IvToolkit-1.3.3-1.12
- jei_1.12.2-4.9.2.196
- LibVulpes-1.12.2-0.2.8-31-universal
- Mantle-1.12-1.3.2.24
- mcjtylib-1.12-3.0.2
- Mekanism-1.12.2-9.4.11.346
- MekanismGenerators-1.12.2-9.4.11.346
- MekanismTools-1.12.2-9.4.11.346
- modular-routers-1.12.2-3.1.5
- movingworld-1.12-6.342-full
- MrTJPCore-1.12.2-2.1.3.35-universal
- OpenComputers-MC1.12.2-1.7.2+a7f3ccb8b
- OpenSecurity-MC1.12.2-1.0-12
- OptiFine_1.12.2_HD_U_E2
- ProjectRed-1.12.2-4.9.1.92-Base
- ProjectRed-1.12.2-4.9.1.92-compat
- ProjectRed-1.12.2-4.9.1.92-fabrication
- ProjectRed-1.12.2-4.9.1.92-integration
- ProjectRed-1.12.2-4.9.1.92-lighting
- RecurrentComplex-1.4.7
- RedstoneFlux-1.12-2.0.2.3-universal
- refinedstorage-1.5.34
- ReWIRED-1.0.3
- rftools-1.12-7.54
- SGCraft-1.15.5-forge-release
- TConstruct-1.12.2-2.10.1.87
- ThermalDynamics-1.12.2-2.5.1.14-universal
- ThermalExpansion-1.12.2-5.5.0.29-universal
- ThermalFoundation-1.12.2-2.5.0.19-universal
- Xaeros_Minimap_1.14.9.1_Forge_1.12
- xray-1.12.2-1.5.0
- zerocore-1.12-0.1.2.2

**Comment by Dockter** [comment]
I believe this was already fixed long ago.
