### ISSUE TITLE
Crash when generating stargate at jungle temple

### ISSUE THREAD

**Issue by x26nexus** [AlmuraDev/SGCraft#80]
[16:53:23] [Client thread/INFO] [net.minecraft.client.gui.GuiNewChat]: [CHAT] Reinforce телепортирован в точку 2712.5 ,75.0, 4104.5
[16:53:23] [Server thread/INFO] [STDOUT]: [gcewing.sg.generator.FeatureJungleTemple:addAugmentationParts:95]: New Y: BlockPos{x=2695, y=73, z=4105}
[16:53:23] [Server thread/INFO] [STDOUT]: [gcewing.sg.generator.FeatureJungleTemple:addAugmentationParts:95]: New Y: BlockPos{x=2695, y=73, z=4105}
[16:53:23] [Server thread/INFO] [STDOUT]: [gcewing.sg.generator.FeatureJungleTemple:addAugmentationParts:95]: New Y: BlockPos{x=2695, y=73, z=4105}
[16:53:23] [Server thread/INFO] [STDOUT]: [gcewing.sg.generator.FeatureJungleTemple:addAugmentationParts:95]: New Y: BlockPos{x=2695, y=74, z=4105}
[16:53:23] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Exception ticking world
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:762) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) ~[MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185) ~[chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
Caused by: java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770) ~[guava-21.0.jar:?]
	at gcewing.sg.generator.GeneratorAddressRegistry.addAddress(GeneratorAddressRegistry.java:70) ~[GeneratorAddressRegistry.class:?]
	at gcewing.sg.generator.FeatureJungleTemple.addAugmentationParts(FeatureJungleTemple.java:148) ~[FeatureJungleTemple.class:?]
	at gcewing.sg.generator.FeatureJungleTemple.func_74875_a(FeatureJungleTemple.java:81) ~[FeatureJungleTemple.class:?]
	at net.minecraft.world.gen.structure.StructureStart.func_75068_a(StructureStart.java:47) ~[bby.class:?]
	at net.minecraft.world.gen.structure.MapGenStructure.func_175794_a(MapGenStructure.java:94) ~[bbu.class:?]
	at net.minecraft.world.gen.ChunkGeneratorOverworld.func_185931_b(ChunkGeneratorOverworld.java:416) ~[aze.class:?]
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1019) ~[axw.class:?]
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:980) ~[axw.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157) ~[on.class:?]
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126) ~[ot.class:?]
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:147) ~[ou.class:?]
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227) ~[oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756) ~[MinecraftServer.class:?]
	... 4 more
[16:53:23] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: This crash report has been saved to: D:\Games\Minecraft\.minecraft\crash-reports\crash-2019-04-17_16.53.23-server.txt
[16:53:23] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Stopping server
[16:53:23] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving players
[16:53:23] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:553]: ---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// Don't be sad, have a hug! <3

Time: 4/17/19 4:53 PM
Description: Exception ticking world

java.lang.NullPointerException: Exception ticking world
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770)
	at gcewing.sg.generator.GeneratorAddressRegistry.addAddress(GeneratorAddressRegistry.java:70)
	at gcewing.sg.generator.FeatureJungleTemple.addAugmentationParts(FeatureJungleTemple.java:148)
	at gcewing.sg.generator.FeatureJungleTemple.func_74875_a(FeatureJungleTemple.java:81)
	at net.minecraft.world.gen.structure.StructureStart.func_75068_a(StructureStart.java:47)
	at net.minecraft.world.gen.structure.MapGenStructure.func_175794_a(MapGenStructure.java:94)
	at net.minecraft.world.gen.ChunkGeneratorOverworld.func_185931_b(ChunkGeneratorOverworld.java:416)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1019)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:980)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:147)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770)
	at gcewing.sg.generator.GeneratorAddressRegistry.addAddress(GeneratorAddressRegistry.java:70)
	at gcewing.sg.generator.FeatureJungleTemple.addAugmentationParts(FeatureJungleTemple.java:148)
	at gcewing.sg.generator.FeatureJungleTemple.func_74875_a(FeatureJungleTemple.java:81)
	at net.minecraft.world.gen.structure.StructureStart.func_75068_a(StructureStart.java:47)
	at net.minecraft.world.gen.structure.MapGenStructure.func_175794_a(MapGenStructure.java:94)
	at net.minecraft.world.gen.ChunkGeneratorOverworld.func_185931_b(ChunkGeneratorOverworld.java:416)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1019)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:980)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:147)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227)

-- Affected level --
Details:
	Level name: Копия мира Survi2
	All players: 1 total; [EntityPlayerMP['Reinforce'/6949, l='Копия мира Survi2', x=2712.50, y=75.00, z=4104.50]]
	Chunk stats: ServerChunkCache: 350 Drop: 0
	Level seed: 6987270715205414477
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-244,64,261), Chunk: (at 12,4,5 in -16,16; contains blocks -256,0,256 to -241,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 4307 game time, 4307 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 169448 (now: false), thunder time: 164323 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_201, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 510916824 bytes (487 MB) / 1038876672 bytes (990 MB) up to 2112618496 bytes (2014 MB)
	JVM Flags: 11 total; -Xincgc -Xms1024M -Xmx2048M -XX:+UseConcMarkSweepGC -XX:-UseAdaptiveSizePolicy -XX:+CMSParallelRemarkEnabled -XX:+ParallelRefProcEnabled -XX:+CMSClassUnloadingEnabled -XX:+UseCMSInitiatingOccupancyOnly -Xmx2048M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 1, tcache: 1, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2825 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID        | Version      | Source                        | Signature                                |
	|:------ |:--------- |:------------ |:----------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft | 1.12.2       | minecraft.jar                 | None                                     |
	| LCHIJA | mcp       | 9.42         | minecraft.jar                 | None                                     |
	| LCHIJA | FML       | 8.0.99.99    | forge-1.12.2-14.23.5.2825.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge     | 14.23.5.2825 | forge-1.12.2-14.23.5.2825.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | sgcraft   | 1.13.2       | SGCraft-2.0.0-beta-4.jar      | None                                     |

	Loaded coremods (and transformers): 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['Reinforce'/6949, l='Копия мира Survi2', x=2712.50, y=75.00, z=4104.50]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
[16:53:23] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:553]: #@!@# Game crashed! Crash report saved to: #@!@# D:\Games\Minecraft\.minecraft\crash-reports\crash-2019-04-17_16.53.23-server.txt
[16:53:23] [Client thread/INFO] [FML]: Waiting for the server to terminate/save.
[16:53:23] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving worlds
[16:53:23] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving chunks for level 'Копия мира Survi2'/overworld
[16:53:24] [Server thread/INFO] [FML]: Unloading dimension 0
[16:53:24] [Server thread/INFO] [FML]: Applying holder lookups
[16:53:24] [Server thread/INFO] [FML]: Holder lookups applied
[16:53:24] [Server thread/INFO] [FML]: The state engine was in incorrect state SERVER_STOPPING and forced into state SERVER_STOPPED. Errors may have been discarded.
[16:53:24] [Client thread/INFO] [FML]: Server terminated.
[16:53:24] [Client Shutdown Thread/INFO] [net.minecraft.server.MinecraftServer]: Stopping server
[16:53:24] [Client Shutdown Thread/INFO] [net.minecraft.server.MinecraftServer]: Saving players

![2019-04-17_16 58 00](https://user-images.githubusercontent.com/19288315/56293832-8b9b9880-6132-11e9-9089-dc29d77addfa.png)

**Comment by Dockter** [comment]
Fixed in Beta 5.
